blank_issues_enabled: false
contact_links:
  - name: General Support
    url: https://github.com/100-hours-a-week/2-leo-park-community-fe/issues
    about: For general support, please visit our support page.
  - name: Email
    url: mailto:byeonghunpark@snu.ac.kr
    about: For direct inquiries, contact us via email.